### ISSUE TITLE
Problems Installing

### ISSUE THREAD

**Issue by samapriya** [monirz/conget#1]
Hi there,
this looks like a great project I tried to follow the following steps to install and getting below-mentioned errors. Another question I had was does this always need a direct link or can it handle redirects?

```go get -v github.com/urfave/cli```

followed by

```
go get github.com/monirz/conget
github.com/monirz/conget (download)
github.com/monirz/conget/vendor/github.com/urfave/cli
github.com/monirz/conget/downloader
# github.com/monirz/conget/downloader
C:\go-work\src\github.com\monirz\conget\downloader\bar.go:28:30: not enough arguments in call to syscall.Syscall
C:\go-work\src\github.com\monirz\conget\downloader\bar.go:28:31: undefined: syscall.SYS_IOCTL
C:\go-work\src\github.com\monirz\conget\downloader\bar.go:28:66: undefined: syscall.TIOCGWINSZ```

**Comment by monirz** [comment]
Hello, currently it doesn't support windows, may be later and yes it needs direct link to download a file.

**Comment by hellokaton** [comment]
I had this problem on the osx.

```bash
» ./conget -u http://h264.u.qiniudn.com/hobbit2.mp4

2018/04/02 13:47:40 conget.go:66: error mime: invalid media parameter
```

**Comment by monirz** [comment]
@biezhi Fixed it. Please let me know if it works now.

**Comment by hellokaton** [comment]
@monirz 
thanks, I can download this file. However, the interface will get stuck to a certain degree, and I can't know whether it is finished or not. I have tried it several times.

![image](https://user-images.githubusercontent.com/3849072/38228098-399d5c5e-3734-11e8-8d2f-e4d13b5db91d.png)

![image](https://user-images.githubusercontent.com/3849072/38228172-9385cec2-3734-11e8-83d2-19ce0a166dcf.png)

It will stop here and nothing will happen.

**Comment by monirz** [comment]
It seems like the link of the server you provided is closing some connections, although its very minimal number of request but some server is configured this way. I tried with a workaround if it still doesn't work, it should now print the error and exit properly. Please let me know what happens now when you try and checkout to dev branch before you try. This update is in the dev branch.

**Comment by monirz** [comment]
OK, updates are on master branch now, blocking from error channel is fixed. And What I see here is your link of the server  just works fine but sometimes it gives error when the net connection speed  is slower. It's kind of weird but that's how the server is behaving, it's resetting the connection when it gets multiple connection opened and some of them are waiting or just slower. That's not usual but I have to add a work around for that. Please try this now and let me know what happens. :)
