### ISSUE TITLE
"panic: runtime error: index out of range" when Content-Disposition does not exist in response header

### ISSUE THREAD

**Issue by maddie** [monirz/conget#2]
https://github.com/monirz/conget/blob/fa088cf8aaaa5faffabc086af743bd246e997edb/downloader/downloader.go#L136

repro: `conget -u http://releases.ubuntu.com/16.04.4/ubuntu-16.04.4-desktop-amd64.iso`

**Comment by monirz** [comment]
Fixed it, I should have added a check for this map key earlier. The error is happening when there's no key named Content-Disposition  in the Header map, it will not happen for all the link though, good catch! And please let me know if it works properly now.

**Comment by maddie** [comment]
Thanks!
